# Generated by Django 5.2.15 on 2026-06-29 22:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('document_url', models.CharField(blank=True, default='', max_length=500)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='TPAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.TextField()),
                ('service_type', models.CharField(choices=[('google', 'Google')], max_length=150)),
            ],
        ),
    ]
