# Generated by Django 5.2.5 on 2025-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TPAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.TextField()),
                ('service_type', models.CharField(choices=[('google', 'Google')], max_length=150)),
            ],
        ),
    ]
