# Generated by Django 5.2.15 on 2026-07-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_interest_hierarchy_and_normalization'),
        ('newsfeed', '0003_alter_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInterestLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('content_processing', 'Content Processing')], default='manual', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.interest')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'interest'), name='unique_post_interest')],
            },
        ),
    ]
