# Generated by Django 5.2.15 on 2026-07-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_backfill_diary_tag_grant_overrides'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interest',
            new_name='interests_i_parent__f549cd_idx',
            old_name='diary_tag_parent__7aae4d_idx',
        ),
        migrations.RenameIndex(
            model_name='interest',
            new_name='interests_i_normali_605a2e_idx',
            old_name='diary_tag_normali_1c6f04_idx',
        ),
        migrations.AlterField(
            model_name='entrytaglink',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.interest'),
        ),
        migrations.AlterModelTable(
            name='entrytaglink',
            table='interests_entrytaglink',
        ),
        migrations.AlterModelTable(
            name='interest',
            table='interests_interest',
        ),
    ]
