# Generated by Django 5.2.15 on 2026-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0006_interests_own_physical_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinterestlink',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('content_processing', 'Content Processing'), ('hashtag', 'Hashtag')], default='manual', max_length=20),
        ),
    ]
