# Generated by Django 5.2.5 on 2026-01-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_mapview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.mood'),
        ),
    ]
