# Generated by Django 5.2.5 on 2026-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_entry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
