# Generated by Django 5.2.5 on 2026-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_attachment_file_id_attachment_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
