# Generated by Django 5.2.15 on 2026-06-29 22:08

import community.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('realm_id', models.CharField(default='417220978101694', max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('profile', models.CharField(default='N/A')),
                ('cover_photo', models.CharField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('email', models.CharField(blank=True, default=None, null=True)),
                ('slug', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('type', models.CharField(choices=[('community', 'Community'), ('page', 'Page'), ('server', 'Server'), ('group', 'Group'), ('conference', 'Conference')], max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ranking_score', models.FloatField(db_index=True, default=0.0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_as_created_by', to='entity.entity')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realms', to='entity.entity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='community.realm', to_field='realm_id')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(default='member', max_length=150)),
                ('date_joined', models.DateTimeField(null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_as_added_by', to='entity.entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.realm')),
            ],
            options={
                'unique_together': {('entity', 'realm')},
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('invite', 'Invite'), ('request', 'Request')], default='invite', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=150)),
                ('target_email', models.EmailField(db_index=True, max_length=254)),
                ('invite_token', models.CharField(default=community.models.generate_invite_token, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realm_invites_accepted', to='entity.entity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_invites_created', to='entity.entity')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realm_invites_targeted', to='entity.entity')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_invites', to='community.realm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['realm', 'target_email'], name='community_i_realm_i_16a81c_idx'), models.Index(fields=['realm', 'invite_token'], name='community_i_realm_i_5dcab8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealmFollow',
            fields=[
                ('follow_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction_score', models.FloatField(default=10.0)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_follows', to='entity.entity')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='community.realm')),
            ],
            options={
                'unique_together': {('follower', 'realm')},
            },
        ),
    ]
