# Generated by Django 5.2.5 on 2025-08-24 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0018_alter_connection_connection_id_alter_connection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('realm_id', models.CharField(default='r4720146837', max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('profile', models.CharField(default='N/A')),
                ('type', models.CharField(choices=[('community', 'Community'), ('page', 'Page'), ('server', 'Server'), ('group', 'Group')], max_length=150)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_as_created_by', to='user.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='community.realm', to_field='realm_id')),
            ],
        ),
    ]
