# Generated by Django 5.2.5 on 2025-08-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realm',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='884980008771329', max_length=150, unique=True),
        ),
    ]
