# Generated by Django 5.2.5 on 2025-08-24 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_realm_is_active_realm_is_private_realm_is_verified_and_more'),
        ('user', '0021_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='293349331183908', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_as_member', to='user.account')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_as_added_by', to='user.account')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.realm')),
            ],
        ),
    ]
