# Generated by Django 5.2.15 on 2026-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_backfill_realm_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='type',
            field=models.CharField(choices=[('page', 'Page'), ('server', 'Server'), ('group', 'Group'), ('conference', 'Conference'), ('channel', 'Channel'), ('voice', 'Voice')], max_length=150),
        ),
    ]
