# Generated by Django 5.2.5 on 2025-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_realm_realm_id_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='374779074677050', max_length=150, unique=True),
        ),
    ]
