# Generated by Django 5.2.15 on 2026-07-07 12:11

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_realm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='id',
            field=models.CharField(blank=True, default=community.models.generate_realm_uid, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
