# Generated by Django 5.2.15 on 2026-07-22 22:54
#
# STATE-ONLY: RealmFollow moved to the entity app. The physical table
# (community_realmfollow) is deliberately NOT dropped - the model is only
# unregistered from this app's migration state and re-registered under
# entity/0007, which pins db_table to the same table. No data is touched and
# no downtime is involved.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_realm_id_alter_realm_realm_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='RealmFollow',
                ),
            ],
        ),
    ]
