# Generated by Django 5.2.5 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='349049438239209', max_length=150, unique=True),
        ),
    ]
