# Generated by Django 5.2.5 on 2025-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='277663982698050', max_length=150, unique=True),
        ),
    ]
