# Generated by Django 5.2.5 on 2025-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='933853735509952', max_length=150, unique=True),
        ),
    ]
