# Generated by Django 5.2.5 on 2025-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='540980148861344', max_length=150, unique=True),
        ),
    ]
