# Generated by Django 5.2.5 on 2025-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='658847106492154', max_length=150, unique=True),
        ),
    ]
