# Generated by Django 5.2.5 on 2025-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='126369145064093', max_length=150, unique=True),
        ),
    ]
