# Generated by Django 5.2.5 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='cover_photo',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='511811403849484', max_length=150, unique=True),
        ),
    ]
