# Generated by Django 5.2.5 on 2025-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_realm_cover_photo_realm_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='776244114396150', max_length=150, unique=True),
        ),
    ]
