# Generated by Django 5.2.5 on 2025-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='616576053819324', max_length=150, unique=True),
        ),
    ]
