# Generated by Django 5.2.5 on 2025-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='401592525416880', max_length=150, unique=True),
        ),
    ]
