# Generated by Django 5.2.5 on 2025-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='198394113996353', max_length=150, unique=True),
        ),
    ]
