# Generated by Django 5.2.5 on 2025-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='330296152719829', max_length=150, unique=True),
        ),
    ]
