# Generated by Django 5.2.5 on 2026-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='868341458817683', max_length=150, unique=True),
        ),
    ]
