# Generated by Django 5.2.5 on 2026-02-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='233343868630899', max_length=150, unique=True),
        ),
    ]
