# Generated by Django 5.2.5 on 2026-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='597256117023524', max_length=150, unique=True),
        ),
    ]
