# Generated by Django 5.2.5 on 2026-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0040_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='596886588337169', max_length=150, unique=True),
        ),
    ]
