# Generated by Django 5.2.5 on 2026-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='821731522300325', max_length=150, unique=True),
        ),
    ]
