# Generated by Django 5.2.5 on 2026-03-18 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0042_alter_realm_realm_id'),
        ('user', '0060_account_user_type_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='237003905067773', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='RealmFollow',
            fields=[
                ('follow_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_follows', to='user.account')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='community.realm')),
            ],
            options={
                'unique_together': {('follower', 'realm')},
            },
        ),
    ]
