# Generated by Django 5.2.5 on 2026-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0043_alter_realm_realm_id_realmfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='member', max_length=150),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='557465019216816', max_length=150, unique=True),
        ),
    ]
