# Generated by Django 5.2.5 on 2026-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_member_role_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='email',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='slug',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='335939536225784', max_length=150, unique=True),
        ),
    ]
