# Generated by Django 5.2.5 on 2026-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0047_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='911369657290269', max_length=150, unique=True),
        ),
    ]
