# Generated by Django 5.2.5 on 2026-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0048_alter_realm_realm_id'),
        ('user', '0067_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='704057802387172', max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('account', 'realm')},
        ),
    ]
