# Generated by Django 5.2.5 on 2026-04-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0049_alter_realm_realm_id_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='949935172582093', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='slug',
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
