# Generated by Django 5.2.5 on 2026-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0050_alter_realm_realm_id_alter_realm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='ranking_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='395341490238318', max_length=150, unique=True),
        ),
    ]
