# Generated by Django 5.2.5 on 2026-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0051_realm_ranking_score_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='500310269649091', max_length=150, unique=True),
        ),
    ]
