# Generated by Django 5.2.5 on 2026-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0052_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='813714898195589', max_length=150, unique=True),
        ),
    ]
