# Generated by Django 5.2.5 on 2026-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0053_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmfollow',
            name='interaction_score',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='realmfollow',
            name='last_interaction_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='966389751730744', max_length=150, unique=True),
        ),
    ]
