# Generated by Django 5.2.5 on 2026-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0054_realmfollow_interaction_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='324577932083888', max_length=150, unique=True),
        ),
    ]
