# Generated by Django 5.2.5 on 2026-06-19 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0055_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='realm',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='realm',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='209164548696349', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='type',
            field=models.CharField(choices=[('community', 'Community'), ('page', 'Page'), ('server', 'Server'), ('group', 'Group'), ('conference', 'Conference')], max_length=150),
        ),
    ]
