# Generated by Django 5.2.5 on 2026-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0056_realm_created_at_realm_expires_at_realm_is_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='starts_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='179174070689577', max_length=150, unique=True),
        ),
    ]
