# Generated by Django 5.2.5 on 2026-06-20 21:55

import community.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0057_realm_starts_at_alter_realm_realm_id'),
        ('user', '0077_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='855193427092409', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('invite', 'Invite'), ('request', 'Request')], default='invite', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=150)),
                ('target_email', models.EmailField(db_index=True, max_length=254)),
                ('invite_token', models.CharField(default=community.models.generate_invite_token, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realm_invites_accepted', to='user.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_invites_created', to='user.account')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_invites', to='community.realm')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realm_invites_targeted', to='user.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['realm', 'target_email'], name='community_i_realm_i_16a81c_idx'), models.Index(fields=['realm', 'invite_token'], name='community_i_realm_i_5dcab8_idx')],
            },
        ),
    ]
