# Generated by Django 5.2.5 on 2026-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0058_alter_realm_realm_id_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='737422868407121', max_length=150, unique=True),
        ),
    ]
