# Generated by Django 5.2.5 on 2026-06-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0060_alter_realm_realm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='realm_id',
            field=models.CharField(default='571254021817233', max_length=150, unique=True),
        ),
    ]
