# Generated by Django 5.2.5 on 2026-06-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0061_alter_realm_realm_id'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='realmfollow',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='realm_follows', to='entity.entity'),
        ),
    ]
