# Generated by Django 5.2.5 on 2025-08-25 11:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0022_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(blank=True, default='6840736632790448542230032', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('file_type', models.CharField(max_length=50)),
                ('caption', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=50)),
                ('is_tagged', models.BooleanField(default=False)),
                ('privacy_status', models.CharField(max_length=50)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('on_feed', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_system', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('map_view_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('is_stationary', models.BooleanField(default=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_info', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostPrivacy',
            fields=[
                ('privacy_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('allowed_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_users', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostReference',
            fields=[
                ('reference_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('reference', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('reference_media_type', models.CharField(max_length=50)),
                ('reference_name', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('post_tag_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='newsfeed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
    ]
