# Generated by Django 5.2.15 on 2026-06-29 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedIndex',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendingPool',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('emoji_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('emoji_title', models.CharField(default='none', max_length=20)),
                ('emoji_content', models.CharField(max_length=20)),
                ('emoji_tags', models.CharField(max_length=1000)),
                ('emoji_theme', models.CharField(default='#7d7d7d')),
                ('priority', models.IntegerField(default=0)),
                ('animated_preview', models.CharField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(blank=True, default='3555366812466081536493174', max_length=150, primary_key=True, serialize=False, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('file_type', models.CharField(max_length=50)),
                ('caption', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=50)),
                ('is_tagged', models.BooleanField(default=False)),
                ('privacy_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('custom', 'Custom')], default='public', max_length=50)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('on_feed', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_system', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_deleted_by', to='user.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('map_view_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('is_stationary', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_info', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_by_account', to='entity.entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.entity')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newsfeed.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostPrivacy',
            fields=[
                ('privacy_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('allowed_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.entity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_users', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostReference',
            fields=[
                ('reference_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('reference', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('reference_media_type', models.CharField(max_length=50)),
                ('reference_name', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_score', models.FloatField(default=1.0)),
                ('content_type_weight', models.FloatField(default=1.0)),
                ('recent_update_boost', models.FloatField(default=1.0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('ranking_score', models.FloatField(db_index=True, default=0.0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('post_tag_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.entity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagging', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewCount',
            fields=[
                ('preview_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsfeed.emoji')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='newsfeed.post')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCount',
            fields=[
                ('count_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('count_type', models.CharField(choices=[('comment', 'Comment'), ('share', 'Share')])),
                ('count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_counts', to='newsfeed.post')),
            ],
            options={
                'unique_together': {('post', 'count_type')},
            },
        ),
        migrations.CreateModel(
            name='PostSave',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.entity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_post', to='newsfeed.post')),
            ],
            options={
                'unique_together': {('post', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newsfeed.emoji')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.entity')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='newsfeed.post')),
            ],
            options={
                'unique_together': {('post', 'entity')},
            },
        ),
    ]
