# Generated by Django 5.2.5 on 2025-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postprivacy',
            old_name='allowed_user_id',
            new_name='allowed_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3281452556680912917407768', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
