# Generated by Django 5.2.15 on 2026-07-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3525905593853342626950254', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
