# Generated by Django 5.2.5 on 2025-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_rename_allowed_user_id_postprivacy_allowed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='2850857839320886170407917', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
