# Generated by Django 5.2.15 on 2026-07-07 13:51

import newsfeed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default=newsfeed.models.generate_post_id, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
