# Generated by Django 5.2.5 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='7030487486139904516681700', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
