# Generated by Django 5.2.15 on 2026-07-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_postinterestlink'),
        ('newsfeed', '0003_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='posts', through='interests.PostInterestLink', to='interests.interest'),
        ),
    ]
