# Generated by Django 5.2.5 on 2025-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='6640647058760519127219238', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
