# Generated by Django 5.2.5 on 2025-09-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0006_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='6357178562332784169601523', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('custom', 'Custom')], default='public', max_length=50),
        ),
    ]
