# Generated by Django 5.2.5 on 2025-09-21 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_alter_post_post_id_alter_post_privacy_status'),
        ('user', '0029_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='6391747625579425386885743', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('emoji_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('emoji_title', models.CharField(default='none', max_length=20)),
                ('emoji_content', models.CharField(max_length=20)),
                ('emoji_tags', models.CharField(max_length=1000)),
                ('emoji_theme', models.CharField(default='#7d7d7d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newsfeed.emoji')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='newsfeed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
