# Generated by Django 5.2.5 on 2025-09-21 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_alter_post_post_id_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3365383585129741430914513', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PreviewCount',
            fields=[
                ('preview_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsfeed.emoji')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='newsfeed.post')),
            ],
        ),
    ]
