# Generated by Django 5.2.5 on 2025-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0011_alter_post_post_id_alter_posttag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='1246332549900918622698537', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
