# Generated by Django 5.2.5 on 2025-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='6972595410866247530595341', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
