# Generated by Django 5.2.5 on 2025-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9955696274728372070427334', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
