# Generated by Django 5.2.5 on 2025-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0015_emoji_priority_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='animated_preview',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='1493982308942380406344789', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
