# Generated by Django 5.2.5 on 2025-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0016_emoji_animated_preview_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='8900535982891789117433209', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
