# Generated by Django 5.2.5 on 2025-11-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0017_alter_comment_updated_at_alter_post_post_id'),
        ('user', '0039_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_by_account', to='user.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3841735603319430351714834', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
