# Generated by Django 5.2.5 on 2025-11-14 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0018_alter_comment_deleted_by_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='5371811113913800996327476', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityCount',
            fields=[
                ('count_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('count_type', models.CharField(choices=[('comment', 'Comment'), ('share', 'Share')])),
                ('count', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_counts', to='newsfeed.post')),
            ],
            options={
                'unique_together': {('post', 'count_type')},
            },
        ),
    ]
