# Generated by Django 5.2.5 on 2025-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0019_alter_post_post_id_activitycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ranking_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='2276981116984454232551282', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
