# Generated by Django 5.2.5 on 2025-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0020_post_ranking_score_alter_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ranking_score',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='4336235609577975680639732', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
