# Generated by Django 5.2.5 on 2025-11-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0021_remove_post_ranking_score_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='1281637296598753388193455', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PostScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_score', models.FloatField(default=1.0)),
                ('content_type_weight', models.FloatField(default=1.0)),
                ('recent_update_boost', models.FloatField(default=1.0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('ranking_score', models.FloatField(db_index=True, default=0.0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='newsfeed.post')),
            ],
        ),
    ]
