# Generated by Django 5.2.5 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0022_alter_post_post_id_postscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='5237742469313049857514498', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
