# Generated by Django 5.2.5 on 2025-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0023_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9658710558772940723523374', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
