# Generated by Django 5.2.5 on 2025-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0024_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3085680384695716194629268', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
