# Generated by Django 5.2.5 on 2025-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0025_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='8862113118404079043393421', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
