# Generated by Django 5.2.5 on 2025-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0026_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='7286196946772049622838138', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
