# Generated by Django 5.2.5 on 2025-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0027_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapview',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mapview',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9651974564145097403676641', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
