# Generated by Django 5.2.5 on 2025-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0029_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='8644497759000170809240430', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
