# Generated by Django 5.2.5 on 2026-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0030_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9926467699992687291163982', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
