# Generated by Django 5.2.5 on 2026-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0031_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='1785956540631355828583091', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
