# Generated by Django 5.2.5 on 2026-02-10 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0034_alter_post_post_id'),
        ('user', '0056_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='4833921585869390743459320', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('log_id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('commented', 'Commented'), ('reacted', 'Reacted'), ('shared', 'Shared')], max_length=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='newsfeed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'user'], name='newsfeed_en_post_id_5bdca2_idx'), models.Index(fields=['user', 'post', 'created_at'], name='newsfeed_en_user_id_b7a60c_idx'), models.Index(fields=['post', 'reference_id'], name='newsfeed_en_post_id_58c016_idx'), models.Index(fields=['user', 'action', 'created_at'], name='newsfeed_en_user_id_8aad53_idx')],
            },
        ),
    ]
