# Generated by Django 5.2.5 on 2026-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0035_alter_post_post_id_engagementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementlog',
            name='duration_seconds',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9148390960139370442928971', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
