# Generated by Django 5.2.5 on 2026-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0036_engagementlog_duration_seconds_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='7242516669047836894219408', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
