# Generated by Django 5.2.5 on 2026-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0037_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3337074542402473653094015', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
