# Generated by Django 5.2.5 on 2026-03-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0043_alter_realm_realm_id_realmfollow'),
        ('newsfeed', '0038_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='community.realm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3103378065785588123110339', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
