# Generated by Django 5.2.5 on 2026-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0039_post_author_realm_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='5147974808003008656267722', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
