# Generated by Django 5.2.5 on 2026-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0040_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='7221646529693694999290937', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
