# Generated by Django 5.2.5 on 2026-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0041_alter_post_post_id'),
        ('user', '0065_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='4900764754681157756561029', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='engagementlog',
            constraint=models.UniqueConstraint(condition=models.Q(('action', 'viewed')), fields=('user', 'post', 'action'), name='unique_viewed_engagement'),
        ),
    ]
