# Generated by Django 5.2.5 on 2026-04-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0042_engagementlog_updated_at_alter_post_post_id_and_more'),
        ('user', '0066_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_deleted_by', to='user.account'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3334800438937284490185139', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
