# Generated by Django 5.2.5 on 2026-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0043_post_deleted_at_post_deleted_by_post_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3186501348172170278278542', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
