# Generated by Django 5.2.5 on 2026-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0045_alter_post_post_id_postsave'),
        ('user', '0069_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='4097024945532462950922677', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='postsave',
            unique_together={('post', 'user')},
        ),
    ]
