# Generated by Django 5.2.5 on 2026-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0047_alter_post_post_id_alter_postsave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='2958306384035415450678225', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
