# Generated by Django 5.2.5 on 2026-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0048_alter_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsfeedIndex',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3407014986922760144367280', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
