# Generated by Django 5.2.5 on 2026-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0049_newsfeedindex_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='8110772552011150123877648', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
