# Generated by Django 5.2.5 on 2026-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0050_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='5515214866786405607744342', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
