# Generated by Django 5.2.5 on 2026-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0051_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3787202156507193491468380', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='EngagementLog',
        ),
    ]
