# Generated by Django 5.2.5 on 2026-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0052_alter_post_post_id_delete_engagementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPool',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='3168568754937548789494163', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
