# Generated by Django 5.2.5 on 2026-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0053_trendingpool_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='1906508975337932026818074', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
