# Generated by Django 5.2.5 on 2026-06-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0054_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='9286458232604757584991670', max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
