# Generated by Django 5.2.5 on 2026-06-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
        ('newsfeed', '0056_alter_post_post_id'),
        ('user', '0082_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='acted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_acted_by', to='user.account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='post',
            name='acted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_acted_by', to='user.account'),
        ),
        migrations.AddField(
            model_name='post',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='postsave',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saved_posts', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='acted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reactions_acted_by', to='user.account'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='actor_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reactions', to='entity.entity'),
        ),
    ]
