# Generated by Django 5.2.15 on 2026-08-30 06:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0014_report_realm_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('handle', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('profile', models.CharField(default='none', max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='entity.entity')),
                ('owner_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_bots', to='entity.entity')),
            ],
            options={
                'indexes': [models.Index(fields=['owner_entity'], name='bot_owner_idx')],
            },
        ),
    ]
