# Generated by Django 5.2.15 on 2026-09-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
