# Generated by Django 5.2.15 on 2026-09-17 10:24

import bot.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, digits and hyphens only.', regex='^[a-z0-9-]{1,32}$')])),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('system', 'System'), ('webhook', 'Webhook'), ('bot', 'Bot')], default='bot', max_length=20)),
                ('responds', models.CharField(choices=[('none', 'Nothing'), ('system', 'The system bot'), ('bot', 'The owning bot')], default='bot', max_length=20)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500)),
                ('webhook_request', models.JSONField(blank=True, default=bot.models.default_webhook_request)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bot.bot')),
            ],
            options={
                'db_table': 'bot_commands',
                'indexes': [models.Index(fields=['name', 'is_active'], name='botcmd_name_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('bot', 'name'), name='botcmd_unique_per_bot'), models.CheckConstraint(condition=models.Q(models.Q(('category', 'webhook'), _negated=True), models.Q(('webhook_url', ''), _negated=True), _connector='OR'), name='botcmd_webhook_has_url'), models.CheckConstraint(condition=models.Q(('category', 'webhook'), ('webhook_url', ''), _connector='OR'), name='botcmd_url_only_on_webhook')],
            },
        ),
    ]
