"""
Django settings for user_service project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from cassandra.auth import PlainTextAuthProvider

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

DB_HOST = os.getenv("DB_HOST")
DB_NAME = os.getenv("DB_NAME")
DB_PORT = os.getenv("DB_PORT")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")

CASSANDRA_DB_HOST = os.getenv("CASSANDRA_DB_HOST")
CASSANDRA_DB_NAME = os.getenv("CASSANDRA_DB_NAME")
CASSANDRA_DB_KEYSPACE = os.getenv("CASSANDRA_DB_KEYSPACE") or CASSANDRA_DB_NAME
CASSANDRA_DB_PORT = os.getenv("CASSANDRA_DB_PORT")
CASSANDRA_DB_USERNAME = os.getenv("CASSANDRA_DB_USERNAME")
CASSANDRA_DB_PASSWORD = os.getenv("CASSANDRA_DB_PASSWORD")
CASSANDRA_DB_TOKEN = os.getenv("CASSANDRA_DB_TOKEN")
CASSANDRA_DB_BUNDLE = os.getenv("CASSANDRA_DB_BUNDLE")
CASSANDRA_DB_ENDPOINT = os.getenv("CASSANDRA_DB_ENDPOINT")


def build_cassandra_bundle_path():
    if not CASSANDRA_DB_BUNDLE:
        raise ValueError("CASSANDRA_DB_BUNDLE is not set.")

    bundle_path = Path(BASE_DIR) / CASSANDRA_DB_BUNDLE
    if not bundle_path.exists():
        raise FileNotFoundError(
            f"Astra secure connect bundle not found at {bundle_path}"
        )

    return bundle_path


def build_cassandra_auth_provider():
    if not CASSANDRA_DB_TOKEN:
        raise ValueError("CASSANDRA_DB_TOKEN is not set.")

    return PlainTextAuthProvider("token", CASSANDRA_DB_TOKEN)


CASSANDRA_BUNDLE_PATH = build_cassandra_bundle_path()
CASSANDRA_AUTH_PROVIDER = build_cassandra_auth_provider()
CASSANDRA_CLOUD_CONFIG = {
    "secure_connect_bundle": str(CASSANDRA_BUNDLE_PATH),
}

DEBUG = os.getenv("DEBUG")
SECRET_KEY = os.getenv("SECRET_KEY")

GUNICORN_MAX_REQUESTS = os.getenv("GUNICORN_MAX_REQUESTS")
SILKY_PYTHON_PROFILER = os.getenv("SILKY_PYTHON_PROFILER")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_USERNAME = os.getenv("REDIS_USERNAME")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

MONGODB_CLUSTER_USER = os.getenv("MONGODB_CLUSTER_USER")
MONGODB_CLUSTER_PASS = os.getenv("MONGODB_CLUSTER_PASS")
MONGODB_CLUSTER_HOST = os.getenv("MONGODB_CLUSTER_HOST")
MONGODB_DB = os.getenv("MONGODB_DB")

MAILINGSERVICE = os.getenv("MAILINGSERVICE")

JWT_TOKEN = os.getenv("JWT_TOKEN")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Default Credentials (for noreply)
EMAIL_HOST_USER = os.getenv("EMAIL_NOREPLY_USER")
EMAIL_HOST_PASSWORD = JWT_TOKEN
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Additional Credentials for Manual Use (for verify)
EMAIL_VERIFY_USER = os.getenv("EMAIL_VERIFY_USER")
EMAIL_VERIFY_PASS = JWT_TOKEN

CSRF_TRUSTED_ORIGINS = ["https://*.chatterloop.app", "https://*.neonsystems.net"]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0",  # Change if needed
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django_cassandra_engine",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "rest_framework",
    "corsheaders",
    # Added apps
    "user",
    "community",
    "newsfeed",
    "core",
    "diary",
    # Silk
    "silk",
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "silk.middleware.SilkyMiddleware",
]

CORS_ALLOWED_ORIGINS = []

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://([a-zA-Z0-9-]+\.)*chatterloop\.app$",
    r"^https://([a-zA-Z0-9-]+\.)*neonsystems\.net$",
    r"^http://localhost:5173$",
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-access-token",
    "paginated",
    "action",
    "x-nonce",
]

ROOT_URLCONF = "user_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "user_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USERNAME,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    },
    "cassandra": {
        "ENGINE": "django_cassandra_engine",
        "NAME": CASSANDRA_DB_KEYSPACE,
        "HOST": CASSANDRA_DB_HOST,
        "PORT": CASSANDRA_DB_PORT,
        "USER": "token",
        "PASSWORD": CASSANDRA_DB_TOKEN,
        "OPTIONS": {
            "connection": {
                "cloud": CASSANDRA_CLOUD_CONFIG,
                "auth_provider": CASSANDRA_AUTH_PROVIDER,
            }
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "user.backends.AutheticationBackend",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/hour",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]
