# Generated by Django 5.2.15 on 2026-06-29 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('user', 'user'), ('bot', 'bot'), ('realm', 'realm')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
