# Generated by Django 5.2.5 on 2026-06-28 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('realm', 'Realm')], db_index=True, max_length=50)),
                ('source_type', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entity',
                'indexes': [models.Index(fields=['entity_type'], name='entity_entity__a3d905_idx'), models.Index(fields=['source_type', 'source_id'], name='entity_source__afdb9c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('entity_type', ''), _negated=True), name='entity_type_not_empty'), models.CheckConstraint(condition=models.Q(('source_type', ''), _negated=True), name='entity_source_type_not_empty'), models.CheckConstraint(condition=models.Q(('source_id', ''), _negated=True), name='entity_source_id_not_empty')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
    ]
