# Generated by Django 5.2.15 on 2026-07-06 18:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_member_role'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPermission',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=150)),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny')], max_length=10)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_created', to='entity.entity')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='entity.entity')),
                ('realm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='community.realm')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'permission', 'realm'], name='entity_enti_entity__2248f6_idx'), models.Index(fields=['entity', 'permission'], name='entity_enti_entity__39ca75_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'permission', 'realm'), name='unique_entity_permission_scope')],
            },
        ),
    ]
