# Generated by Django 5.2.15 on 2026-07-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_seed_permission_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissioncatalogentry',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('realm', 'Realm'), ('entity_type', 'Entity Type')], max_length=20),
        ),
        migrations.CreateModel(
            name='EntityTypeDefaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'user'), ('bot', 'bot'), ('realm', 'realm')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_type_grants', to='entity.permissioncatalogentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'permission'), name='unique_entity_type_permission')],
            },
        ),
    ]
