# Generated by Django 5.2.15 on 2026-07-22 22:54
#
# STATE-ONLY: adopts Connection (from the user app) and RealmFollow (from the
# community app) into the entity app. Both were already entity-keyed models,
# so this is a pure ownership move - database_operations is empty and each
# model pins db_table to its ORIGINAL physical table (user_connection /
# community_realmfollow). Nothing is created, dropped, or copied; the Node
# server's raw SQL against those table names keeps resolving.
#
# Renaming the physical tables to entity_connections / entity_followers is a
# deliberately separate migration, so this move stays independently
# reversible and can ship without coordinating a Node deploy.

import django.db.models.deletion
import django.utils.timezone
import entity.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_delete_realmfollow'),
        ('entity', '0006_seed_entity_type_module_permissions'),
        ('user', '0004_delete_connection'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Connection',
                    fields=[
                        ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                        ('connection_id', models.CharField(default=entity.models.generate_connection_id, max_length=150)),
                        ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                        ('status', models.BooleanField(default=True)),
                        ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                        ('type', models.CharField(choices=[('single', 'Single')], max_length=150)),
                        ('interaction_score', models.FloatField(default=10.0)),
                        ('last_interaction_at', models.DateTimeField(auto_now=True)),
                        ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_action_by', to='entity.entity')),
                        ('involved_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_involved_entity', to='entity.entity')),
                    ],
                    options={
                        'db_table': 'user_connection',
                    },
                ),
                migrations.CreateModel(
                    name='Follow',
                    fields=[
                        ('follow_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('interaction_score', models.FloatField(default=10.0)),
                        ('last_interaction_at', models.DateTimeField(auto_now=True)),
                        ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realm_follows', to='entity.entity')),
                        ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='community.realm')),
                    ],
                    options={
                        'db_table': 'community_realmfollow',
                        'unique_together': {('follower', 'realm')},
                    },
                ),
            ],
        ),
    ]
