# Generated by Django 5.2.15 on 2026-07-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_connection_realmfollow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
