# Generalises Follow from "entity follows REALM" to "entity follows ENTITY".
#
# The old `realm_id` column stored a Realm pk. The new `followee_id` stores an
# entity id, so a follow can target a person as well as a page. Existing rows
# are converted in place by resolving each realm to its entity - no data is
# dropped and no table is recreated.
#
# Hand-written rather than autogenerated: makemigrations would prompt
# interactively about whether realm->followee is a rename (it is not - the FK
# target model changes, and the stored values have to be translated).

from django.db import migrations, models
import django.db.models.deletion


def backfill_followee(apps, schema_editor):
    """realm_id (a Realm pk) -> followee_id (that realm's entity id)."""
    Follow = apps.get_model("entity", "Follow")
    Realm = apps.get_model("community", "Realm")

    # One query for the whole mapping instead of a lookup per row.
    realm_to_entity = dict(Realm.objects.values_list("id", "entity_id"))

    to_update = []
    unresolved = []
    for follow in Follow.objects.all():
        entity_id = realm_to_entity.get(follow.realm_id)
        if entity_id:
            follow.followee_id = entity_id
            to_update.append(follow)
        else:
            unresolved.append(follow.pk)

    if to_update:
        Follow.objects.bulk_update(to_update, ["followee_id"], batch_size=500)

    # `realm` was a non-null FK, so this should be empty. Clearing any strays
    # is required before followee can be made non-null.
    if unresolved:
        Follow.objects.filter(pk__in=unresolved).delete()


def reverse_followee(apps, schema_editor):
    """followee_id (entity id) -> realm_id, for rollback."""
    Follow = apps.get_model("entity", "Follow")
    Realm = apps.get_model("community", "Realm")

    entity_to_realm = dict(Realm.objects.values_list("entity_id", "id"))

    to_update = []
    unresolved = []
    for follow in Follow.objects.all():
        realm_id = entity_to_realm.get(follow.followee_id)
        if realm_id:
            follow.realm_id = realm_id
            to_update.append(follow)
        else:
            # A follow of a USER cannot be represented by the old schema.
            unresolved.append(follow.pk)

    if to_update:
        Follow.objects.bulk_update(to_update, ["realm_id"], batch_size=500)

    if unresolved:
        Follow.objects.filter(pk__in=unresolved).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0008_alter_connection_table_alter_follow_table"),
        ("community", "0007_delete_realmfollow"),
    ]

    operations = [
        # Drop the old constraint first - it names `realm`, which is removed
        # below, and the new pair is not unique-safe until backfill completes.
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        # Nullable while the backfill runs.
        migrations.AddField(
            model_name="follow",
            name="followee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="entity.entity",
            ),
        ),
        migrations.RunPython(backfill_followee, reverse_followee),
        migrations.AlterField(
            model_name="follow",
            name="followee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="entity.entity",
            ),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="realm",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followee")},
        ),
    ]
