# Generated by Django 5.2.15 on 2026-09-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_seed_developer_api_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rate_limit_int',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='rate_limit_type',
            field=models.CharField(blank=True, choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=10, null=True),
        ),
    ]
