# Generated by Django 5.2.15 on 2026-06-29 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagementLog',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(default='N/A', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('profile', models.CharField(default='none')),
                ('coverphoto', models.CharField(default='none')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(default=uuid.uuid4, max_length=400)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_badged', models.BooleanField(default=False)),
                ('is_default_user', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.CharField(default='user', max_length=150)),
                ('join_type', models.CharField(default='system', max_length=150)),
                ('connection_count', models.IntegerField(default=0)),
                ('ranking_score', models.FloatField(db_index=True, default=0.0)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('connection_id', models.CharField(default='53439595628066756830', max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(default=True)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('single', 'Single')], max_length=150)),
                ('interaction_score', models.FloatField(default=10.0)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_action_by', to='entity.entity')),
                ('involved_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_involved_entity', to='entity.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('message', 'Message')], max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('hate_speech', 'Hate speech'), ('violence', 'Violence or dangerous behavior'), ('nudity', 'Nudity or sexual content'), ('csae', 'Child sexual abuse or exploitation'), ('impersonation', 'Impersonation'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_received', to='entity.entity')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_filed', to='entity.entity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_reviewed', to='entity.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('document_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consents', to='entity.entity')),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('ver_id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('ver_code', models.CharField(default='95156', max_length=6)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.account')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocked_by', to='entity.entity')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks_made', to='entity.entity')),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
