# Generated by Django 5.2.5 on 2025-08-23 17:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(blank=True, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(default='N/A', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birthdate', models.DateTimeField()),
                ('profile', models.CharField(default='N/A')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default_user', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
