# Generated by Django 5.2.5 on 2025-08-23 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
