# Generated by Django 5.2.15 on 2026-07-22 22:54
#
# STATE-ONLY: Connection moved to the entity app. The physical table
# (user_connection) is deliberately NOT dropped - the model is only
# unregistered from this app's migration state and re-registered under
# entity/0007, which pins db_table to the same table. No data is touched and
# the Node server's raw SQL against user_connection keeps working.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Connection',
                ),
            ],
        ),
    ]
