# Generated by Django 5.2.15 on 2026-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
