# Generated by Django 5.2.5 on 2025-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='25725', max_length=6),
        ),
    ]
