# Generated by Django 5.2.5 on 2025-08-23 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='36016', max_length=6),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_id',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('connection_id', models.CharField(default=uuid.uuid4, max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('single', 'Single'), ('group', 'Group'), ('server', 'Server')], max_length=150)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_action_by', to='user.account')),
                ('involved_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections_as_involved_user', to='user.account')),
            ],
        ),
    ]
