# Generated by Django 5.2.5 on 2025-08-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_connections_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='35925', max_length=6),
        ),
    ]
