# Generated by Django 5.2.5 on 2025-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='45291', max_length=6),
        ),
    ]
