# Generated by Django 5.2.5 on 2025-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_connection_nickname_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('group', 'Group')], max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='84734', max_length=6),
        ),
    ]
