# Generated by Django 5.2.5 on 2025-08-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_connection_type_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='13667', max_length=6),
        ),
    ]
