# Generated by Django 5.2.5 on 2025-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_verification_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='2344015758', max_length=150),
        ),
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('single', 'Single')], max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='92001', max_length=6),
        ),
    ]
