# Generated by Django 5.2.5 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='7509286451', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='17733', max_length=6),
        ),
    ]
