# Generated by Django 5.2.5 on 2025-09-06 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_account_is_verified_alter_account_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=uuid.uuid4, max_length=400),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='7310009856', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='77535', max_length=6),
        ),
    ]
