# Generated by Django 5.2.5 on 2025-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='65016664259496837437', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='14810', max_length=6),
        ),
    ]
