# Generated by Django 5.2.5 on 2025-10-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='93855927944868745082', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='82807', max_length=6),
        ),
    ]
