# Generated by Django 5.2.5 on 2025-11-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='25817529571546954676', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='98318', max_length=6),
        ),
    ]
