# Generated by Django 5.2.5 on 2025-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='join_type',
            field=models.CharField(default='system', max_length=150),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='86104870705527789455', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='77380', max_length=6),
        ),
    ]
