# Generated by Django 5.2.5 on 2026-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='coverphoto',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='78062475102324898505', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='99632', max_length=6),
        ),
    ]
