# Generated by Django 5.2.5 on 2026-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='29327618512350336676', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='44731', max_length=6),
        ),
    ]
