# Generated by Django 5.2.5 on 2026-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_account_user_type_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_badged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='81666964807274927111', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='63808', max_length=6),
        ),
    ]
