# Generated by Django 5.2.5 on 2026-04-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='37817014042828284736', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='98316', max_length=6),
        ),
    ]
