# Generated by Django 5.2.5 on 2026-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagementLog',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='ranking_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='16953857958103576845', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='41555', max_length=6),
        ),
    ]
