# Generated by Django 5.2.5 on 2026-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_userengagementlog_account_ranking_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='connection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='interaction_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_interaction_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='77764999280333465991', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='90331', max_length=6),
        ),
    ]
