# Generated by Django 5.2.5 on 2026-05-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_account_connection_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='29537330955897454556', max_length=150),
        ),
        migrations.AlterField(
            model_name='connection',
            name='interaction_score',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='90772', max_length=6),
        ),
    ]
