# Generated by Django 5.2.5 on 2026-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_alter_connection_connection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_id',
            field=models.CharField(default='75390103778418733614', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='ver_code',
            field=models.CharField(default='41528', max_length=6),
        ),
    ]
